estudoDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
"""Define padrões de URL para learning_logs."""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views


urlpatterns = [
    # Página de login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Um assunto sobre o qual o usuario esta aprendendo"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    # Esse método é como um ToString do Java.
    def __str__(self):
        """Devolve uma representacao em string do modelo"""
        return self.text


class Entry(models.Model):
    """Algo especifico aprendido sobre o assunto"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    # Meta armazena informações extras para administrar o modelo
    class Meta:
        verbose_name_plural = 'entires'
        # Esse método é como um ToString do Java.
        def __str__(self):
            """Devolve uma representacao em string do modelo"""
            return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.core.urlresolvers import reverse
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required


def index(request):
    """Tela inicial."""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Mostra todos os assuntos."""
    # Quando o usuário está logado, o objeto de requisição tem um atributo 'request.user' definido
    # que armazena informações sobre o usuário.
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    # topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Mostra um único assunto e todas as suas entradas."""
    topic = Topic.objects.get(id=topic_id)
    # Garante que o assunto pertence ao usuário atual.
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Adiciona um novo assunto"""
    if request.method != 'POST':
        # Nenhum dado submetido; cria um formulário em branco
        form = TopicForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = TopicForm(request.POST)
        if form.is_valid():
            # Passando o argumento 'commit=False' modifica o
            # novo assunto antes de salvá-lo no banco de dados
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Acrescenta uma nova entrada para um assunto em particular."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Nenhum dado submetido; cria um formulário em branco
        form = EntryForm()
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(data=request.POST)
        if form.is_valid():
            # Passando o argumento 'commit=False' modifica o
            # novo assunto antes de salvá-lo no banco de dados
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edita uma entrada existente"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Garante que o assunto pertence ao usuário atual.
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Requisição inicial; preenche previamente o formulário com a entrada atual
        form = EntryForm(instance=entry)
    else:
        # Dados de POST submetidos; processa os dados
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Faz logout do usuário"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """Faz o cadastro de um novo usuário"""
    if request.method != 'POST':
        # Exibe o formulário do cadastro em branco
        form = UserCreationForm()
    else:
        # Processa o formulário preenchido
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Faz login de usuário e o redireciona para a página inicial
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning_log</title>
</head>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a>
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
        <!-- No sistema de autenticação de Django, o conjunto de
         templates tem uma variável 'user' diponível. -->
        {% if user.is_authenticated %}
            Hello, {{ user.username }}.
            <a href="{% url 'users:logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'users:register' %}">Register</a>
            <a href="{% url 'users:login' %}">Login</a>
        {% endif %}
    </p>
    {% block content %}
    {% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a></p>
    <p>Edit entry:</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p>Learning Logs helps you keep track of your learning, for any topic you're learning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
        <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p>Add a new topic:</p>
        <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Topic: {{ topic }}</p>
    <p>Entries:</p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ entry.text|linebreaks }}</p>
                <p><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></p>
            </li>
        {% empty %}
            <li>There are no entries for this topic yet</li>
        {% endfor %}
    </ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p>Topics</p>
    <ul>
        {% for topic in topics %}
            <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match, Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Login</button>
        <!-- Elemento de formulário oculto 'next', o argumento 'value' diz
        para onde devemos ir ao fazer login -->
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Register</button>
        <!-- Elemento de formulário oculto 'next', o argumento 'value' diz
        para onde devemos ir ao fazer cadastro -->
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
    </form>
{% endblock content %}